changed
artsdeep/architecture-sprint-8 pull request #1
Opened 2024-11-13 18:59 UTC by artsdeep

2024-11-19 18:04 UTC, kostya05983 commented
Привет, при запуске приложения, не грузится localhost:3000, видимо из-за смены порта keycloack

![image](https://github.com/user-attachments/assets/e6b91f8d-11b1-4836-a623-6d148663ce9a)

2024-11-19 18:19 UTC, artsdeep commented
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/c6390079-f13a-4b61-9f82-67e9719de779">
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/14939915-00a9-408d-bbed-1f8eeb593e88">

я переделал на порт 8085

2024-11-20 04:33 UTC, kostya05983 commented
привет, извиняюсь, отправь на проверку ещё раз, оказалось что image keycloack закэшировался из-за этого и не работало, сегодня утром осознал это

2024-11-20 07:09 UTC, artsdeep commented
Привет! ага, отправил

2024-11-20 16:10 UTC, kostya05983 commented
Артём, в этот раз всё запустилось, но смотри какая проблема, получаю 401 при скачивании отчётов с ролью prothetic_user.

Шаги:
1) Запускаю docker compose up -d --build
2) Иду на localhost:3000
3) Авторизуюсь испоользуя креды prothetic1, prothetic123
4) Жму кнопку download reports
5) Получаю 401, signature verification failed, прикладываю скрин
![image](https://github.com/user-attachments/assets/da216c66-7fde-409d-ad9d-0aa8b9de3a18)

2024-11-20 16:11 UTC, kostya05983 requested changes

2024-11-20 16:11 UTC, kostya05983 commented on api/app/main.py
> +async def get_current_user(credentials: HTTPAuthorizationCredentials = Security(HTTPBearer())):
По неймингу, может что-то вроде get_token? 
а то по факту ведь не пользователя возвращаем из функции

2024-11-20 16:11 UTC, kostya05983 commented on api/app/main.py
> +            detail=f"Could not validate credentials: {e}"
падает вот тут, при нажатии на download reports

2024-11-20 16:16 UTC, artsdeep commented on api/app/main.py
> +async def get_current_user(credentials: HTTPAuthorizationCredentials = Security(HTTPBearer())):
да не очень корректно

2024-11-20 16:19 UTC, artsdeep commented on api/app/main.py
> +            detail=f"Could not validate credentials: {e}"
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/74778add-b71b-4e3b-96c6-a5600ff28894">
а можешь прислать что возвращает запрос http://localhost:8085/realms/reports-realm/protocol/openid-connect/certs ?

2024-11-21 07:43 UTC, kostya05983 commented on api/app/main.py
> +            detail=f"Could not validate credentials: {e}"
Интересно, хотел тебе прислать и всё заработало в этот раз,magic, проверил все сценарии, всё работает. Пришли работу на проверку в практикуме и я поставлю зачёт

2025-02-03 07:16 UTC, merged